package busres;

import javax.swing.JOptionPane;

/**
 *
 * @author gilbe_000
 */
public class Details extends javax.swing.JDialog {

    private String customer_name = "",
            customer_sname = "",
            customer_pnumber = "";
    
    public boolean isDone = false;
    
    
    // ------------------------------- [ C O N S T A N T S ] ------------------------------- //
    
    private final static String TELEPHONE_NUMBER_PATTERN = "([\\+(]?(\\d){2,}[)]?[- \\.]?"
            + "(\\d){2,}[- \\.]?(\\d){2,}[- \\.]?"
            + "(\\d){2,}[- \\.]?(\\d){2,})|([\\+(]?"
            + "(\\d){2,}[)]?[- \\.]?(\\d){2,}[- \\.]?"
            + "(\\d){2,}[- \\.]?(\\d){2,})|([\\+(]?(\\d){2,}[)]?"
            + "[- \\.]?(\\d){2,}[- \\.]?(\\d){2,})";
    
    // ------------------------------- [ C O N S T A N T S ] ------------------------------- //
    
    
    
    // ------------------------------- [ C H E C K I N G ] ------------------------------- //
    
    private boolean isValidPhoneNumber(String pNumber) {
        if(java.util.regex.Pattern.matches(TELEPHONE_NUMBER_PATTERN, pNumber)) return true;
        return false;
    }
    
    private boolean isAnyEmpty() {
        if(name_field.getText().equals("") || 
                sname_field.getText().equals("") ||
                pnumber_field.getText().equals("")) return true;
        return false;
    }
    
    // ------------------------------- [ C H E C K I N G ] ------------------------------- //
    
    private void getDetails() {
        customer_name = name_field.getText();
        customer_sname = sname_field.getText();
        customer_pnumber = pnumber_field.getText();
    }
    
    private void clearStrings() {
        customer_name = customer_sname = customer_pnumber = "";
    }
    
    private void close() {
        java.awt.Container container = name_field.getParent();
        do {
            container = container.getParent();
        } while(!(container instanceof javax.swing.JDialog));
        ((javax.swing.JDialog) container).dispose();
    }
    
    public void setData() {
        String[] data = new String[3];
        
        data[0] = customer_name;
        data[1] = customer_sname;
        data[2] = customer_pnumber;
        
        BusRes.customer_data = data;
    }
    
    public Details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        sname_field = new javax.swing.JTextField();
        pnumber_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel3.setText("Surname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel4.setText("Telephone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel5.setText(" : ");
        getContentPane().add(jLabel5, new java.awt.GridBagConstraints());

        jLabel6.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel6.setText(" : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Avant Garde", 1, 14)); // NOI18N
        jLabel7.setText(" : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(name_field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(sname_field, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(pnumber_field, gridBagConstraints);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearStrings();
        getDetails();
        
        if(isAnyEmpty()) JOptionPane.showMessageDialog(this, "All fields must be filled.", "Error!", JOptionPane.ERROR_MESSAGE);
        else if(!isValidPhoneNumber(customer_pnumber)) JOptionPane.showMessageDialog(this, "Entered phone number is invalid.\n"
                + "Format: + [COUNTRY CODE] [AREA CODE] [NUMBER]\n"
                + "Example: +994 55 5555555", "Error!", JOptionPane.ERROR_MESSAGE);
        else {
            setData();
            BusRes.isDialogDone = true;
            close();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Details dialog = new Details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField pnumber_field;
    private javax.swing.JTextField sname_field;
    // End of variables declaration//GEN-END:variables
}
